language: java
jdk:
    - oraclejdk8
node_js: "0.10"

before_script:
  - pip install --user codecov

script:
  - ./mvnw clean verify -Pintegration-test

#  - ./ui-test.sh

after_success:
  - codecov

addons:
  postgresql: "9.6"
