language: java
jdk:
    - oraclejdk8
node_js: "0.10"

dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.m2

before_script:
  - pip install --user codecov
  - psql -c "ALTER ROLE postgres WITH PASSWORD 'postgres';" -U postgres

script:
  - ./mvnw clean verify -Pintegration-test

#  - ./ui-test.sh

after_success:
  - codecov

addons:
  postgresql: "9.6"
